### ISSUE TITLE
Too much useless dependances in composer

### ISSUE THREAD

**Issue by Identity-labs** [mossadal/math-parser#11]
Package operations: 70 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v3.3.16): Downloading (100%)         
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Downloading (100%)         
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.1.3): Downloading (100%)         
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)         
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)         
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (3.3.3): Downloading (100%)         
  - Installing phpdocumentor/reflection-docblock (2.0.5): Downloading (100%)         
  - Installing phpspec/prophecy (1.7.5): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (5.1.7): Downloading (100%)         
  - Installing nikic/php-parser (v1.4.1): Downloading (100%)         
  - Installing psr/log (1.0.2): Loading from cache
  - Installing phpdocumentor/reflection (3.0.1): Downloading (100%)         
  - Installing symfony/finder (v2.8.36): Downloading (100%)         
  - Installing phpdocumentor/fileset (1.0.0): Downloading (100%)         
  - Installing phpdocumentor/graphviz (1.0.4): Downloading (100%)         
  - Installing zendframework/zend-stdlib (2.7.7): Loading from cache
  - Installing zendframework/zend-hydrator (1.1.0): Loading from cache
  - Installing zendframework/zend-filter (2.7.2): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.0): Downloading (100%)         
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing zendframework/zend-servicemanager (2.7.10): Loading from cache
  - Installing zendframework/zend-cache (2.7.2): Downloading (100%)         
  - Installing zendframework/zend-json (3.1.0): Downloading (100%)         
  - Installing zendframework/zend-serializer (2.8.1): Loading from cache
  - Installing zendframework/zend-i18n (2.7.4): Loading from cache
  - Installing zendframework/zend-config (2.6.0): Loading from cache
  - Installing kherge/version (1.0.1): Downloading (100%)         
  - Installing seld/jsonlint (1.7.1): Downloading (100%)         
  - Installing justinrainbow/json-schema (1.6.1): Downloading (100%)         
  - Installing herrera-io/json (1.0.3): Downloading (100%)         
  - Installing herrera-io/phar-update (1.0.3): Downloading (100%)         
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.4.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Downloading (100%)         
  - Installing phpcollection/phpcollection (0.5.0): Downloading (100%)         
  - Installing jms/parser-lib (1.0.0): Downloading (100%)         
  - Installing jms/metadata (1.6.0): Downloading (100%)         
  - Installing jms/serializer (1.11.0): Downloading (100%)         
  - Installing symfony/filesystem (v3.0.9): Downloading (100%)         
  - Installing symfony/config (v2.8.36): Downloading (100%)         
  - Installing symfony/stopwatch (v2.8.36): Downloading (100%)         
  - Installing symfony/event-dispatcher (v2.8.36): Downloading (100%)         
  - Installing zetacomponents/base (1.9.1): Downloading (100%)         
  - Installing zetacomponents/document (1.3.1): Downloading (100%)         
  - Installing symfony/process (v2.8.36): Downloading (100%)         
  - Installing erusev/parsedown (1.7.1): Downloading (100%)         
  - Installing twig/twig (v1.35.2): Downloading (100%)         
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
  - Installing symfony/debug (v3.0.9): Downloading (100%)         
  - Installing symfony/console (v2.8.36): Downloading (100%)         
  - Installing symfony/translation (v3.0.9): Downloading (100%)         
  - Installing symfony/validator (v2.8.36): Downloading (100%)         
  - Installing pimple/pimple (v1.1.1): Downloading (100%)         
  - Installing cilex/console-service-provider (1.0.0): Downloading (100%)         
  - Installing cilex/cilex (1.1.0): Downloading (100%)         
  - Installing phpdocumentor/phpdocumentor (v2.9.0): Downloading (100%)

**Comment by mossadal** [comment]
I have no idea what you are referring to. The project has no dependencies in production and only phpunit and phpdocumentor in dev which are needed to run the tests and build the full documentation.
