### ISSUE TITLE
PHP_Timer not found, old phpunit version ?

### ISSUE THREAD

**Issue by YziG** [mossadal/math-parser#13]
When I pulled your project, I tried to run the tests and this error occurred:
PHP Fatal error:  Uncaught Error: Class 'PHP_Timer' not found  math-parser/vendor/phpunit/phpunit/src/Framework/TestResult.php:662

I made some researches and I found this recent issue (around 6 months old) about the problem.
https://github.com/sebastianbergmann/phpunit/issues/3008

Apparently, some old phpunit versions can't work with the new version of PHP_Timer. I've tried the conflict param for composer, but it didn't seem to work. I will continue to search a solution.

I must admit that I pulled your project to run the tests because I tried to evaluate round, ceil and floor functions and I got this error:
"MathParser\Exceptions\UnknownVariableException : Unknown variable r." has if round is not a function...

**EDIT**: Well I found out why round, ceil and floor throw exception. They seem to work on dev-master, but not on your last tag (1.3.13). But still nothing for PHP_Timer.

**Comment by mossadal** [comment]
Thank you for the report, I will look into this.
