### ISSUE TITLE
Unexpected results of some expressions

### ISSUE THREAD

**Issue by byCedric** [mossadal/math-parser#2]
First of all, thanks for this great library! I really love how its structured with an AST and the code quality is great! We are using it at the [Larachat's](https://larachat.co/) slackbot ["Eve"](https://github.com/mdavis1982/eve) and encountered some unexpected behaviours. You can view the whole discussion over [here](https://github.com/mdavis1982/eve/issues/30#issuecomment-254002840) btw. Here are the expressions we used, what we expected and the result.

| used | expected | result |
| --- | --- | --- |
| `0 ^ 0` | 1 | _division by zero exception_ |
| `0 * log(0)` | NAN | 0 |

Is this something you would agree on?

**Comment by mossadal** [comment]
Ok, that's a little weird, I will look into it. 

0*log(0) should certainly return NAN or possibly throw an exception. As a mathematician, I prefer to leave 0^0 undefined, even though realize that 0^0=1 is often a useful convention.

**Comment by byCedric** [comment]
Haha, I will never force a mathematician to some common conventions. Thanks for the tip on creating a custom evaluator, will definitely look into it. If I can help, you can message me anytime. Again, thanks for this library and your quick response!

**Comment by mossadal** [comment]
I had a look at the `0*log(0)` issue. It is due to some slightly overaggressive simplification in the parser. I will think of how to fix this without losing some simplifications that I'd like to keep, but it might take a few days.

In the meantime (and for your use case, it won't hurt much), try

~~~
$parser = new StdMathParser(); // or RationalMathParser if you prefer
$parser->setSimplifying(false);
~~~

and `0*log(0)` will evaluate to `NAN` as expected.

**Comment by mossadal** [comment]
Actually, with `setSimplifying(false)`, you will also get `0^0 = 1` for free.

**Comment by byCedric** [comment]
You are the best! If I can help you on something, you can always message me. Thanks you once again for your quick response and good workarounds!

**Comment by byCedric** [comment]
I don't know if this is related or if I should open up a new issue. Right now we have an exception (non math-exception) being thrown when the expression `!1` is being evaluated. 

With version **1.2.3** this threw an `UnknownTokenException: Unknown token 0 encountered in Lexing/Lexer.php on line 85` which is correct. But as of **1.3.3** a `Uncaught Error: Call to a member function accept() on null in Interpreting/Evaluator.php:186` is being thrown. I briefly tried to find the cause, but I'm still searching.

**Comment by mossadal** [comment]
This doesn't seem to be related. 1.3.0 added support for factorials, so "!1" shouldn't throw a `UnknownTokenException`, but it should throw a `SyntaxErrorException` instead. It seems like some malformed expressions containing `!` slips through the Parser. I'll check it out.

**Comment by mossadal** [comment]
@byCedric Thank you for the report, I think that should fix it.

**Comment by byCedric** [comment]
Thank you once again for your quick fix! If you are ever visiting Amsterdam I will buy you a beer or something!

**Comment by mossadal** [comment]
@byCedric Looking forward to it!
