### ISSUE TITLE
improve/fix type hints

### ISSUE THREAD

**Issue by Selion05** [mossadal/math-parser#20]
https://github.com/mossadal/math-parser/blob/61e5ca6a5b6cdf06c1b028ca96bc769670cb952a/src/MathParser/StdMathParser.php#L50

Intelij (idea) doesn't understand  `@retval`.  It works with `@return`. The namespaces are different too.

Are you open for a pr?

**Comment by mossadal** [comment]
Thanks! I'd be happy to accept a pull request.
