### ISSUE TITLE
New Operator request

### ISSUE THREAD

**Issue by F43RY** [mossadal/math-parser#21]
Hi,
how can add a new Operator "pipe ( | )"  that acts as "add ( + )" put 0 whereas a variable is null (or blank)?

This is an example how to get it worked:
a=5, b=null
a+b = null    (actual working)
a|b = 5          (desidered)

Thanks

**Comment by mossadal** [comment]
You can write your own lexer and evaluator based on the ones provided to accomplish that. Create your own copies of StdMathLexer and Evaluator adding your '|' with the same precedence as '+' in the Lexer and code in for evaluating '|' in the Evaluator.
