### ISSUE TITLE
Support PHP 8 

### ISSUE THREAD

**Issue by KevOutIngs** [mossadal/math-parser#28]
Hello @mossadal,

Will you upgrade your project to support PHP 8 as a major release 2.X any time soon ?

Best Regards

**Comment by mossadal** [comment]
A 2.0 release with much improved code quality is in the works. I'm afraid I can't give you a timeline though.

By the way, the current release should work with PHP 8. Does it not? (I'm using it myself in a project that's running on PHP 8.)

**Comment by KevOutIngs** [comment]
I understand thank you for your fast feedback.

I didn’t know for sure if the library supported PHP 8 because you removed it from Travis that’s why I was asking. That’s a great news 

Thank you very much
