### ISSUE TITLE
Improve exception usability

### ISSUE THREAD

**Issue by byCedric** [mossadal/math-parser#3]
Right now the parser has some really useful interpretation exceptions. Unfortunately I found no possibility to get the, let's say an unknown token, from the exception. It's being merged with the exception's message. This forces me to inform an user with a generic error description. 

This can easily be accomplished by adding an exception variable, with an accessor. For example, the token exception could get a public `getToken()` method which will return the token only. If you agree and would like this feature, I can create a pull request for this.

**Comment by mossadal** [comment]
Good idea, I'll be happy to accept that pull request

**Comment by mossadal** [comment]
Thank you for the contribution, it is now merged into master.
