### ISSUE TITLE
Guide for new users

### ISSUE THREAD

**Issue by KrepishRU** [mossadal/math-parser#9]
Hello. Nice lib and examples of code. But how can i start to use it? Do i need compile somehow this code? If i just wanna use it on my web form to prevent some hacks in input (without php eval function). what i need to do to use your lib? Sorry for my bad English

**Comment by KrepishRU** [comment]
ok now i am trying to use Composer on my server. It seams that minimum requirement version of php is 5.6......

**Comment by KrepishRU** [comment]
Ok. After using Composer i got vendor directory. I create index.php file and use this code
 `
<?php
include '../vendor/autoload.php';
use MathParser\StdMathParser;
use MathParser\Interpreting\Evaluator;

$parser = new StdMathParser();

// Generate an abstract syntax tree
$AST = $parser->parse('1+2');

// Do something with the AST, e.g. evaluate the expression:
$evaluator = new Evaluator();

$value = $AST->accept($evaluator);
echo $value;
?>
`

and i got nothing

**Comment by mossadal** [comment]
Sorry, I can't give support on basic usage of composer and general organization of your own code base.
